### ISSUE TITLE
proposte da implementare

### ISSUE THREAD

**Issue by ClaireFrancoise** [riccardonobile/diamondsharps#2]
- Nei dettagli non visualizzare nel momento del caricamento (products, contacts e il trattino messo tra i     contatti)
- Inserire tasto per tornare da dettagli alla lista principale
- Fare in modo che nel momento del login alla pressione del tasto enter sia possibile fare il login senza cliccare il bottone

**Comment by ClaireFrancoise** [comment]
- Mettere caricamento nella pagina principale per caricamento mappa intera

**Comment by simonecragnolini** [comment]
Hi Claire, i've fixed that things:
- Inserire tasto per tornare da dettagli alla lista principale
- Fare in modo che nel momento del login alla pressione del tasto enter sia possibile fare il login senza cliccare il bottone

But i don't understand your last request, can you explain it?
