### ISSUE TITLE
Semi transparent header

### ISSUE THREAD

**Issue by riccardonobile** [riccardonobile/diamondsharps#4]
Make the header semi transparent when you are in the map view of the stores like the example above
![opacity](https://cloud.githubusercontent.com/assets/4092574/14814016/b3d8bdd2-0ba4-11e6-9c89-64d2b7c2de6e.png)
This is done with:
`md-toolbar:not(.md-menu-toolbar) {
background-color: rgba(255,193,7, 0.7); 
}`
and in all widths
`#map {
top: 0;
}`

**Comment by simonecragnolini** [comment]
Yeah, I like it
